name: Build and Deploy

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Cache pnpm store
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Configure SSH
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p ~/.ssh/
          echo "$DROPLET_SSH_KEY" > ~/.ssh/ghactions
          chmod 600 ~/.ssh/ghactions
        env:
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
      - name: Deploy with rsync
        if: github.ref == 'refs/heads/master'
        run: |
          rsync -az --delete \
          -e 'ssh -i ~/.ssh/ghactions -p ${{ secrets.DROPLET_SSH_PORT }} -o StrictHostKeyChecking=no' \
          --backup --backup-dir=${{ secrets.DROPLET_RSYNC_BACKUP_DIRECTORY }} \
          dist/ ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:${{ secrets.DROPLET_RSYNC_APP_DIRECTORY }}
